In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

C:\Users\Waris Hayyat\AppData\Local\Temp\ipykernel_9380\573954172.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

                                    Working with Json

In [25]:
#how to import json file into datafrmae
data=pd.read_json("brazil_geo.json")
data

                 type                                           features
0   FeatureCollection  {'type': 'Feature', 'id': 'AC', 'properties': ...
1   FeatureCollection  {'type': 'Feature', 'id': 'AL', 'properties': ...
2   FeatureCollection  {'type': 'Feature', 'id': 'AP', 'properties': ...
3   FeatureCollection  {'type': 'Feature', 'id': 'AM', 'properties': ...
4   FeatureCollection  {'type': 'Feature', 'id': 'BA', 'properties': ...
5   FeatureCollection  {'type': 'Feature', 'id': 'CE', 'properties': ...
6   FeatureCollection  {'type': 'Feature', 'id': 'DF', 'properties': ...
7   FeatureCollection  {'type': 'Feature', 'id': 'ES', 'properties': ...
8   FeatureCollection  {'type': 'Feature', 'id': 'GO', 'properties': ...
9   FeatureCollection  {'type': 'Feature', 'id': 'MA', 'properties': ...
10  FeatureCollection  {'type': 'Feature', 'id': 'MT', 'properties': ...
11  FeatureCollection  {'type': 'Feature', 'id': 'MS', 'properties': ...
12  FeatureCollection  {'type': 'Feature', 'id': 'MG', 'properties': ...
13  FeatureCollection  {'type': 'Feature', 'id': 'PA', 'properties': ...
14  FeatureCollection  {'type': 'Feature', 'id': 'PB', 'properties': ...
15  FeatureCollection  {'type': 'Feature', 'id': 'PR', 'properties': ...
16  FeatureCollection  {'type': 'Feature', 'id': 'PE', 'properties': ...
17  FeatureCollection  {'type': 'Feature', 'id': 'PI', 'properties': ...
18  FeatureCollection  {'type': 'Feature', 'id': 'RJ', 'properties': ...
19  FeatureCollection  {'type': 'Feature', 'id': 'RN', 'properties': ...
20  FeatureCollection  {'type': 'Feature', 'id': 'RS', 'properties': ...
21  FeatureCollection  {'type': 'Feature', 'id': 'RO', 'properties': ...
22  FeatureCollection  {'type': 'Feature', 'id': 'RR', 'properties': ...
23  FeatureCollection  {'type': 'Feature', 'id': 'SC', 'properties': ...
24  FeatureCollection  {'type': 'Feature', 'id': 'SP', 'properties': ...
25  FeatureCollection  {'type': 'Feature', 'id': 'SE', 'properties': ...
26  FeatureCollection  {'type': 'Feature', 'id': 'TO', 'properties': ...

In [32]:
#Now working with sql first we make database on xamp then import a library on the notebook.

In [35]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     --------------------------------------- 0.0/11.9 MB 146.3 kB/s eta 0:01:21
     --------------------------------------- 0.0/11.9 MB 164.3 kB/s eta 0:01:12
     --------------------------------------- 0.1/11.9 MB 245.8 kB/s eta 0:00:48
     --------------------------------------- 0.1/11.9 MB 345.9 kB/s eta 0:00:34
      -------------------------------------- 0.2/11.9 MB 418.0 kB/s eta 0:00:28
      -------------------------------------- 0.2/11.9 MB 573.4 kB/s eta 0:00:21
      -------------------------------------- 0.3/11.9 MB 632.4 kB/s eta 0:00:19
     - ------------------------------------- 0.4/11.9 MB 719.3 kB/s eta 0:00:16
     - ------------------------------------- 0.4/11.9 MB 755.6 kB/s eta 0:00:16
     -- ------------------------------------- 0.7/11.9 MB 1.2 MB/s eta 0:00:10
     -- ------------------------------------- 0.8/11.9 MB 1.3 MB/s eta 0:00:09
     ---- ----------------------------------- 1.2/11.9 MB 1.8 MB/s eta 0:00:06
     ---- ----------------------------------- 1.5/11.9 MB 2.0 MB/s eta 0:00:06
     ---- ----------------------------------- 1.5/11.9 MB 2.0 MB/s eta 0:00:06
     ---- ----------------------------------- 1.5/11.9 MB 2.0 MB/s eta 0:00:06
     ---- ----------------------------------- 1.5/11.9 MB 2.0 MB/s eta 0:00:06
     ---- ----------------------------------- 1.5/11.9 MB 2.0 MB/s eta 0:00:06
     ----- ---------------------------------- 1.6/11.9 MB 1.7 MB/s eta 0:00:07
     ------ --------------------------------- 2.0/11.9 MB 2.0 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.1 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.1 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.1 MB/s eta 0:00:05
     ------- -------------------------------- 2.2/11.9 MB 1.9 MB/s eta 0:00:06
     ------- -------------------------------- 2.2/11.9 MB 1.9 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/11.9 MB 1.9 MB/s eta 0:00:06
     ---------- ----------------------------- 3.2/11.9 MB 2.4 MB/s eta 0:00:04
     ---------- ----------------------------- 3.2/11.9 MB 2.4 MB/s eta 0:00:04
     ----------- ---------------------------- 3.3/11.9 MB 2.4 MB/s eta 0:00:04
     ----------- ---------------------------- 3.3/11.9 MB 2.4 MB/s eta 0:00:04
     ----------- ---------------------------- 3.4/11.9 MB 2.3 MB/s eta 0:00:04
     ----------- ---------------------------- 3.5/11.9 MB 2.3 MB/s eta 0:00:04
     ------------ --------------------------- 3.6/11.9 MB 2.3 MB/s eta 0:00:04
     ------------ --------------------------- 3.8/11.9 MB 2.3 MB/s eta 0:00:04
     ------------- -------------------------- 4.1/11.9 MB 2.4 MB/s eta 0:00:04
     -------------- ------------------------- 4.2/11.9 MB 2.4 MB/s eta 0:00:04
     -------------- ------------------------- 4.3/11.9 MB 2.4 MB/s eta 0:00:04
     -------------- ------------------------- 4.3/11.9 MB 2.4 MB/s eta 0:00:04
     -------------- ------------------------- 4.3/11.9 MB 2.3 MB/s eta 0:00:04
     --------------- ------------------------ 4.6/11.9 MB 2.4 MB/s eta 0:00:03
     ---------------- ----------------------- 4.8/11.9 MB 2.4 MB/s eta 0:00:03
     ---------------- ----------------------- 4.8/11.9 MB 2.4 MB/s eta 0:00:03
     ---------------- ----------------------- 4.8/11.9 MB 2.4 MB/s eta 0:00:03
     ----------------- ---------------------- 5.2/11.9 MB 2.4 MB/s eta 0:00:03
     ----------------- ---------------------- 5.2/11.9 MB 2.5 MB/s eta 0:00:03
     ----------------- ---------------------- 5.2/11.9 MB 2.5 MB/s eta 0:00:03
     ------------------ --------------------- 5.4/11.9 MB 2.4 MB/s eta 0:00:03
     ------------------ --------------------- 5.5/11.9 MB 2.4 MB/s eta 0:00:03
     ------------------ --------------------- 5.5/11.9 MB 2.4 MB/s eta 0:00:03
     ------------------- -------------------- 5.6/11.9 MB 2.4 MB/s eta 0:00:03
     ------------------- -------------------- 5.7/11.9 MB 2.3 MB/s eta 0:00:03
     ------------------- -------------------- 5.8/11.9 MB 2.3 MB/s eta 0:00:03
     ------------------- -------------------- 5.9/11.9 MB 2.3 MB/s eta 0:00:03
     ------------------- -------------------- 5.9/11.9 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.0/11.9 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.1/11.9 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.1/11.9 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.2/11.9 MB 2.3 MB/s eta 0:00:03
     --------------------- ------------------ 6.3/11.9 MB 2.2 MB/s eta 0:00:03
     --------------------- ------------------ 6.4/11.9 MB 2.2 MB/s eta 0:00:03
     --------------------- ------------------ 6.5/11.9 MB 2.2 MB/s eta 0:00:03
     --------------------- ------------------ 6.5/11.9 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 6.7/11.9 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 6.8/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 6.8/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 6.9/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 7.0/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.2/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.2/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.3/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.4/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.4/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------- -------------- 7.5/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------- -------------- 7.6/11.9 MB 2.1 MB/s eta 0:00:03
     -------------------------- ------------- 7.7/11.9 MB 2.1 MB/s eta 0:00:02
     -------------------------- ------------- 7.8/11.9 MB 2.1 MB/s eta 0:00:02
     -------------------------- ------------- 8.0/11.9 MB 2.1 MB/s eta 0:00:02
     -------------------------- ------------- 8.0/11.9 MB 2.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 2.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.2/11.9 MB 2.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.2/11.9 MB 2.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.3/11.9 MB 2.1 MB/s eta 0:00:02
     ---------------------------- ----------- 8.4/11.9 MB 2.1 MB/s eta 0:00:02
     ---------------------------- ----------- 8.4/11.9 MB 2.1 MB/s eta 0:00:02
     ---------------------------- ----------- 8.5/11.9 MB 2.0 MB/s eta 0:00:02
     ---------------------------- ----------- 8.6/11.9 MB 2.0 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.0 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.0 MB/s eta 0:00:02
     ----------------------------- ---------- 8.8/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------ --------- 9.0/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------ --------- 9.0/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------ --------- 9.1/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------- -------- 9.2/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------- -------- 9.3/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.0 MB/s eta 0:00:02
     -------------------------------- ------- 9.5/11.9 MB 2.0 MB/s eta 0:00:02
     -------------------------------- ------- 9.6/11.9 MB 2.0 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.0 MB/s eta 0:00:02
     --------------------------------- ------ 9.8/11.9 MB 2.0 MB/s eta 0:00:01
     --------------------------------- ------ 9.9/11.9 MB 2.0 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 2.0 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 2.0 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------- ----- 10.1/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------- ----- 10.3/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------- ----- 10.3/11.9 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.4/11.9 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.6/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 10.8/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 10.9/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.1/11.9 MB 2.0 MB/s eta 0:00:01
     ------------------------------------- -- 11.2/11.9 MB 2.0 MB/s eta 0:00:01
     -------------------------------------- - 11.4/11.9 MB 2.0 MB/s eta 0:00:01
     -------------------------------------- - 11.4/11.9 MB 2.0 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.6/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247958 sha256=e931dd9abe7242300b989c63ff63f4d1e8887df41315a5f265ea02926681e7c8
  Stored in directory: c:\users\waris hayyat\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [36]:
import mysql.connector

In [40]:
connection=mysql.connector.Connect(host="localhost",user="root",password="",database="world")

In [101]:
City=pd.read_sql_query("SELECT * FROM CITY WHERE  ",connection)
City

C:\Users\Waris Hayyat\AppData\Local\Temp\ipykernel_9380\3110173952.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  City=pd.read_sql_query("SELECT * FROM CITY where name like 'india' ",connection)

Empty DataFrame
Columns: [ID, Name, CountryCode, District, Population]
Index: []

In [65]:
Country=pd.read_sql_query("SELECT * FROM COUNTRY",connection)
Country

C:\Users\Waris Hayyat\AppData\Local\Temp\ipykernel_9380\3128894736.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Country=pd.read_sql_query("SELECT * FROM COUNTRY",connection)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [51]:
language=pd.read_sql_query("SELECT * FROM COUNTRYLANGUAGE",connection)
language

C:\Users\Waris Hayyat\AppData\Local\Temp\ipykernel_9380\1623803578.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  language=pd.read_sql_query("SELECT * FROM COUNTRYLANGUAGE",connection)

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [69]:
City,Country

(        ID            Name CountryCode       District  Population
 0        1           Kabul         AFG          Kabol     1780000
 1        2        Qandahar         AFG       Qandahar      237500
 2        3           Herat         AFG          Herat      186800
 3        4  Mazar-e-Sharif         AFG          Balkh      127800
 4        5       Amsterdam         NLD  Noord-Holland      731200
 ...    ...             ...         ...            ...         ...
 4074  4075      Khan Yunis         PSE     Khan Yunis      123175
 4075  4076          Hebron         PSE         Hebron      119401
 4076  4077        Jabaliya         PSE     North Gaza      113901
 4077  4078          Nablus         PSE         Nablus      100231
 4078  4079           Rafah         PSE          Rafah       92020

 [4079 rows x 5 columns],
     Code          Name      Continent                     Region  SurfaceArea  \
 0    ABW         Aruba  North America                  Caribbean        193.0
 1    AFG   Afghanistan           Asia  Southern and Central Asia     652090.0
 2    AGO        Angola         Africa             Central Africa    1246700.0
 3    AIA      Anguilla  North America                  Caribbean         96.0
 4    ALB       Albania         Europe            Southern Europe      28748.0
 ..   ...           ...            ...                        ...          ...
 234  YEM         Yemen           Asia                Middle East     527968.0
 235  YUG    Yugoslavia         Europe            Southern Europe     102173.0
 236  ZAF  South Africa         Africa            Southern Africa    1221037.0
 237  ZMB        Zambia         Africa             Eastern Africa     752618.0
 238  ZWE      Zimbabwe         Africa             Eastern Africa     390757.0

      IndepYear  Population  LifeExpectancy       GNP    GNPOld  \
 0          NaN      103000            78.4     828.0     793.0
 1       1919.0    22720000            45.9    5976.0       NaN
 2       1975.0    12878000            38.3    6648.0    7984.0
 3          NaN        8000            76.1      63.2       NaN
 4       1912.0     3401200            71.6    3205.0    2500.0
 ..         ...         ...             ...       ...       ...
 234     1918.0    18112000            59.8    6041.0    5729.0
 235     1918.0    10640000            72.4   17000.0       NaN
 236     1910.0    40377000            51.1  116729.0  129092.0
 237     1964.0     9169000            37.2    3377.0    3922.0
 238     1980.0    11669000            37.8    5951.0    8670.0

                  LocalName                                GovernmentForm  \
 0                    Aruba  Nonmetropolitan Territory of The Netherlands
 1    Afganistan/Afqanestan                               Islamic Emirate
 2                   Angola                                      Republic
 3                 Anguilla                 Dependent Territory of the UK
 4                Shqipëria                                      Republic
 ..                     ...                                           ...
 234               Al-Yaman                                      Republic
 235            Jugoslavija                              Federal Republic
 236           South Africa                                      Republic
 237                 Zambia                                      Republic
 238               Zimbabwe                                      Republic

                  HeadOfState  Capital Code2
 0                    Beatrix    129.0    AW
 1              Mohammad Omar      1.0    AF
 2    José Eduardo dos Santos     56.0    AO
 3               Elisabeth II     62.0    AI
 4             Rexhep Mejdani     34.0    AL
 ..                       ...      ...   ...
 234       Ali Abdallah Salih   1780.0    YE
 235       Vojislav Koštunica   1792.0    YU
 236              Thabo Mbeki    716.0    ZA
 237        Frederick Chiluba   3162.0    ZM
 238         Robert G. Mugabe   4068.0    ZW

 [239 rows x 15 columns])

In [84]:
var = pd.merge(City, Country, on='Name')
print(var.columns.value_counts().sum())

19

In [76]:
var2=pd.merge(var,language, on="CountryCode")

In [77]:
var2

,ID,Name,CountryCode,District,Population_x,Code,Continent,Region,SurfaceArea,IndepYear,...,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,Language,IsOfficial,Percentage
0,585,Djibouti,DJI,Djibouti,383000,DJI,Africa,Eastern Africa,23200.0,1977.0,...,382.0,373.0,Djibouti/Jibuti,Republic,Ismail Omar Guelleh,585.0,DJ,Afar,F,34.8
1,585,Djibouti,DJI,Djibouti,383000,DJI,Africa,Eastern Africa,23200.0,1977.0,...,382.0,373.0,Djibouti/Jibuti,Republic,Ismail Omar Guelleh,585.0,DJ,Arabic,T,10.6
2,585,Djibouti,DJI,Djibouti,383000,DJI,Africa,Eastern Africa,23200.0,1977.0,...,382.0,373.0,Djibouti/Jibuti,Republic,Ismail Omar Guelleh,585.0,DJ,Somali,F,43.9
3,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Bicol,F,5.7
4,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Cebuano,F,23.3
5,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Hiligaynon,F,9.1
6,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Ilocano,F,9.3
7,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Maguindanao,F,1.4
8,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Maranao,F,1.3
9,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Pampango,F,3.0
10,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Pangasinan,F,1.8
11,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Pilipino,T,29.3
12,864,Mexico,PHL,Central Luzon,109481,MEX,North America,Central America,1958201.0,1810.0,...,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Waray-waray,F,3.8
13,915,Gibraltar,GIB,–,27025,GIB,Europe,Southern Europe,6.0,NaN,...,258.0,NaN,Gibraltar,Dependent Territory of the UK,Elisabeth II,915.0,GI,Arabic,F,7.4
14,915,Gibraltar,GIB,–,27025,GIB,Europe,Southern Europe,6.0,NaN,...,258.0,NaN,Gibraltar,Dependent Territory of the UK,Elisabeth II,915.0,GI,English,T,88.9
15,2272,Armenia,COL,Quindío,288977,ARM,Asia,Middle East,29800.0,1991.0,...,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126.0,AM,Arawakan,F,0.1
16,2272,Armenia,COL,Quindío,288977,ARM,Asia,Middle East,29800.0,1991.0,...,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126.0,AM,Caribbean,F,0.1
17,2272,Armenia,COL,Quindío,288977,ARM,Asia,Middle East,29800.0,1991.0,...,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126.0,AM,Chibcha,F,0.4
18,2272,Armenia,COL,Quindío,288977,ARM,Asia,Middle East,29800.0,1991.0,...,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126.0,AM,Creole English,F,0.1
19,2272,Armenia,COL,Quindío,288977,ARM,Asia,Middle East,29800.0,1991.0,...,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126.0,AM,Spanish,T,99.0
20,2429,Kuwait,KWT,al-Asima,28859,KWT,Asia,Middle East,17818.0,1961.0,...,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW,Arabic,T,78.1
21,2429,Kuwait,KWT,al-Asima,28859,KWT,Asia,Middle East,17818.0,1961.0,...,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW,English,F,0.0
22,2454,Macao,MAC,Macau,437500,MAC,Asia,Eastern Asia,18.0,NaN,...,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO,Canton Chinese,F,85.6
23,2454,Macao,MAC,Macau,437500,MAC,Asia,Eastern Asia,18.0,NaN,...,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO,English,F,0.5
24,2454,Macao,MAC,Macau,437500,MAC,Asia,Eastern Asia,18.0,NaN,...,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO,Mandarin Chinese,F,1.2
25,2454,Macao,MAC,Macau,437500,MAC,Asia,Eastern Asia,18.0,NaN,...,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO,Portuguese,T,2.3
26,3171,San Marino,SMR,San Marino,2294,SMR,Europe,Southern Europe,61.0,885.0,...,510.0,NaN,San Marino,Republic,None,3171.0,SM,Italian,T,100.0
27,3208,Singapore,SGP,–,4017733,SGP,Asia,Southeast Asia,618.0,1965.0,...,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208.0,SG,Chinese,T,77.1
28,3208,Singapore,SGP,–,4017733,SGP,Asia,Southeast Asia,618.0,1965.0,...,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208.0,SG,Malay,T,14.1
29,3208,Singapore,SGP,–,4017733,SGP,Asia,Southeast Asia,618.0,1965.0,...,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208.0,SG,Tamil,T,7.4